[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  framework = "#static"   # tells Netlify to just serve static + functions
  port = 8888             # ensure consistent local dev port
